spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/junitstudy
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    open-in-view: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      '[org.springframework.web]': DEBUG
      '[org.hibernate]': DEBUG

